image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$HOST_NAME","$HOST_KEY" > ~/.ssh/known_hosts 
  - chmod 644 ~/.ssh/known_hosts
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - rm -rf ./assets/data
  - rm -rf ./static/data
  - scp -rv ${USER}@${HOST_NAME}:$RESOURCES_DIR/assets-data ./assets/data
  - scp -rv ${USER}@${HOST_NAME}:$RESOURCES_DIR/static-data ./static/data

install_dependencies:
  stage: .pre
  script:
    - npm install

generate:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist/

resume:
  stage: deploy
  script:
    - - scp -rv ./dist/* ${USER}@{$HOST_NAME}:$DEPLOY_LOCAL/

pages:
  stage: deploy
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
