image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - "rm -rf ./assets/data"
  - "cp -rv $RESOURCES_DIR/assets-data ./assets/data"
  - "rm -rf ./static/data"
  - "cp -rv $RESOURCES_DIR/static-data ./static/data"

install_dependencies:
  stage: .pre
  script:
    - npm install

generate:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist/

resume:
  stage: deploy
  script:
    - cp -rv ./dist/* $DEPLOY_LOCAL/

pages:
  stage: deploy
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
