image: node:latest

variables:
  BASE_URL: "./"

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - npm install

lint:
  stage: .pre
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

unit_test:
  stage: test
  script:
    - npm run test

coverage:
  stage: test
  script:
    - npm run coverage
