image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - npm install

lint:
  stage: .pre
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build

generate:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist/
