language: node_js

node_js:
  - node

cache:
  npm: true

install:
  - cp -rv ./assets/data-sample ./assets/data
  - cp -rv ./static/data-sample ./static/data
  - npm install
  - npm run lint

script:
  - npm run build
  - npm run generate
